name: Python application test with Github Actions
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       repository: come2niks/python-for-devops
       token: ${{ secrets.PAT }}
       ref: master
    - name: Set up Python 3.10
      uses: actions/setup/python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        # make lint
    - name: Test with python 
      run: |
        # make test
    - name: Format code
      run: |
        # make format
